version: '3'

services:
  apache:
    image: httpd
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - php

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - apache

  php:
    image: php:7.2-fpm
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb
